services:
  api:
    build: ./server
    depends_on:
      db:
        condition: service_started
        restart: true
    environment:
      PORT: 3000
      JWT_SECRET: askjldfjaskldjasl
      DRIVER: postgres
      DATABASE_URL: postgres://admin:password@db:5432/versionflow

    volumes: 
      - ./server:/app

  web:
    build: ./web
    volumes:
      - ./web:/app

  db:
    image: postgres:17.2-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: versionflow
    logging:
      driver: none
    volumes:
      - ./.docker-data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  drizzle_studio:
    build: 
      context: ./server
      dockerfile: drizzle.Dockerfile
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/versionflow
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_started
        restart: true
    volumes: 
      - ./server:/app

  
  caddy:
    image: caddy:2.8.4-alpine
    logging:
      driver: none
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.docker-data/caddy:/data

